apiVersion: apps/v1
kind: Deployment
metadata:
  name: perjava
spec:
  selector:
    matchLabels:
      app: perjava
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: perjava
    spec:
      containers:
      - name: perjava
        image: pradeepcoeb/nodeapp:latest
        ports:
        - containerPort: 8085
